SERVERLESS_AWS_LAMBDA_OTEL_EXTENSION_NAME = "serverless-aws-lambda-otel-extension"

_X_AMZN_TRACE_ID_ENV_VAR = "_X_AMZN_TRACE_ID"

AWS_DEFAULT_REGION_ENV_VAR = "AWS_DEFAULT_REGION"
AWS_LAMBDA_FUNCTION_MEMORY_SIZE_ENV_VAR = "AWS_LAMBDA_FUNCTION_MEMORY_SIZE"
AWS_LAMBDA_FUNCTION_NAME_ENV_VAR = "AWS_LAMBDA_FUNCTION_NAME"
AWS_LAMBDA_FUNCTION_VERSION_ENV_VAR = "AWS_LAMBDA_FUNCTION_VERSION"
AWS_LAMBDA_LOG_GROUP_NAME_ENV_VAR = "AWS_LAMBDA_LOG_GROUP_NAME"
AWS_LAMBDA_LOG_STREAM_NAME_ENV_VAR = "AWS_LAMBDA_LOG_STREAM_NAME"
AWS_LAMBDA_RUNTIME_API_ENV_VAR = "AWS_LAMBDA_RUNTIME_API"
AWS_REGION_ENV_VAR = "AWS_REGION"

EXTENSIONS_API_REGISTER_URL_ENV_VAR = "EXTENSIONS_API_REGISTER_URL"
EXTENSIONS_API_NEXT_URL_ENV_VAR = "EXTENSIONS_API_NEXT_URL"
LOGS_API_REGISTER_URL_ENV_VAR = "LOGS_API_REGISTER_URL"

SLS_OTEL_RESOURCE_ATTRIBUTES_ENV_VAR = "SLS_OTEL_RESOURCE_ATTRIBUTES"

SLS_LOG_SERVER_HOST_ENV_VAR = "SLS_LOG_SERVER_HOST"
SLS_LOG_SERVER_PORT_ENV_VAR = "SLS_LOG_SERVER_PORT"
SLS_LOG_SERVER_URL_ENV_VAR = "SLS_LOG_SERVER_URL"
SLS_OTEL_SERVER_HOST_ENV_VAR = "SLS_OTEL_SERVER_HOST"
SLS_OTEL_SERVER_PORT_ENV_VAR = "SLS_OTEL_SERVER_PORT"
SLS_OTEL_SERVER_URL_ENV_VAR = "SLS_OTEL_SERVER_URL"

TEST_DRY_LOG_ENV_VAR = "TEST_DRY_LOG"

# These should be dot.ted instead of snake_case
SLS_OTEL_RESOURCE_ATTRIBUTES_ORG_ID_VAR = "sls_org_id"
SLS_OTEL_RESOURCE_ATTRIBUTES_SERVICE_NAME_VAR = "sls_service_name"
SLS_OTEL_RESOURCE_ATTRIBUTES_STAGE_VAR = "sls_stage"

LAMBDA_EXTENSION_NAME_HEADER = "Lambda-Extension-Name"
LAMBDA_EXTENSION_IDENTIFIER_HEADER = "Lambda-Extension-Identifier"
LAMBDA_EXTENSION_FUNCTION_ERROR_TYPE_HEADER = "Lambda-Extension-Function-Error-Type"

EXTENSIONS_API_EVENT_NEXT_PATH = "2020-01-01/extension/event/next"
EXTENSIONS_API_EXIT_ERROR_PATH = "2020-01-01/extension/exit/error"
EXTENSIONS_API_INIT_ERROR_PATH = "2020-01-01/extension/init/error"
EXTENSIONS_API_REGISTER_PATH = "2020-01-01/extension/register"

LOGS_API_PATH = "2020-08-15/logs"

HTTP_CONTENT_TYPE_APPLICATION_JSON = "application/json"
HTTP_CONTENT_TYPE_HEADER = "Content-Type"

HTTP_METHOD_GET = "GET"
HTTP_METHOD_POST = "POST"
HTTP_METHOD_PUT = "PUT"

TRUTHY = ["true", "1", "1.0", "yes", "on", "yup", "mmhmm"]
