import typing

SLS_OPENTELEMETRY_SERVER_URL = "http://sandbox.localdomain:2772"
SLS_LOG_SERVER_URL = "http://sandbox.localdomain:4243"

SLS_OTEL_RESOURCE_ATTRIBUTES_ORG_ID = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
SLS_OTEL_RESOURCE_ATTRIBUTES_SERVICE_NAME = "undefined"
SLS_OTEL_RESOURCE_ATTRIBUTES_STAGE = "undefined"

SLS_OTEL_RESOURCE_ATTRIBUTES = ""

AWS_REGION = "us-east-1"

AWS_LAMBDA_FUNCTION_NAME = "Fake"
AWS_LAMBDA_FUNCTION_VERSION = "LATEST"
AWS_LAMBDA_FUNCTION_TIMEOUT = 6
AWS_LAMBDA_FUNCTION_ARN = "arn:aws:lambda:serverless:Fake"
AWS_LAMBDA_FUNCTION_MEMORY_SIZE = 1024
AWS_LAMBDA_FUNCTION_REQUEST_ID = "1234567890"
AWS_LAMBDA_FUNCTION_LOG_GROUP_NAME = "/aws/lambda/Fake"

OTEL_PYTHON_DISABLED_INSTRUMENTATIONS: typing.List[str] = []
