DEF_SLS_EXTENSION_COLLECTOR_URL = "http://localhost:2772"

DEF_SLS_EXTENSION_METRICS_ENABLED = False

DEF_SLS_EXTENSION_LOG_LEVEL = "critical"

# Currently Unused.
DEF_SLS_OPENTELEMETRY_HTTP_REQUEST_TIMEOUT = 5
