import os

from serverless.aws_lambda_otel_extension.shared.constants import (
    _HANDLER_ENV_VAR,
    AWS_DEFAULT_REGION_ENV_VAR,
    AWS_LAMBDA_FUNCTION_MEMORY_SIZE_ENV_VAR,
    AWS_LAMBDA_FUNCTION_NAME_ENV_VAR,
    AWS_LAMBDA_FUNCTION_VERSION_ENV_VAR,
    AWS_LAMBDA_LOG_GROUP_NAME_ENV_VAR,
    AWS_LAMBDA_LOG_STREAM_NAME_ENV_VAR,
    AWS_REGION_ENV_VAR,
    ORIG_HANDLER_ENV_VAR,
    OTEL_PYTHON_DISABLED_INSTRUMENTATIONS_ENV_VAR,
    OTEL_PYTHON_ENABLED_INSTRUMENTATIONS_ENV_VAR,
    OTEL_PYTHON_LOG_CORRELATION_ENV_VAR,
    SLS_CONSOLE_SETTINGS_ENV_VAR,
    SLS_EXTENSION_COLLECTOR_URL_ENV_VAR,
    SLS_EXTENSION_FLUSH_TIMEOUT_ENV_VAR,
    SLS_EXTENSION_LOG_LEVEL_ENV_VAR,
    TEST_DRY_LOG_ENV_VAR,
    TEST_DRY_LOG_PRETTY_ENV_VAR,
)

ENV_AWS_LAMBDA_FUNCTION_MEMORY_SIZE = os.getenv(AWS_LAMBDA_FUNCTION_MEMORY_SIZE_ENV_VAR)
ENV_AWS_LAMBDA_FUNCTION_NAME = os.getenv(AWS_LAMBDA_FUNCTION_NAME_ENV_VAR)
ENV_AWS_LAMBDA_FUNCTION_VERSION = os.getenv(AWS_LAMBDA_FUNCTION_VERSION_ENV_VAR)
ENV_AWS_LAMBDA_LOG_GROUP_NAME = os.getenv(AWS_LAMBDA_LOG_GROUP_NAME_ENV_VAR)
ENV_AWS_LAMBDA_LOG_STREAM_NAME = os.getenv(AWS_LAMBDA_LOG_STREAM_NAME_ENV_VAR)

# We may want to alter this to fetch from a boto3.Session instance instead of environment variables to enable better
# local testing.
ENV_AWS_DEFAULT_REGION = os.getenv(AWS_DEFAULT_REGION_ENV_VAR)
ENV_AWS_REGION = os.getenv(AWS_REGION_ENV_VAR)

ENV_TEST_DRY_LOG = os.getenv(TEST_DRY_LOG_ENV_VAR)
ENV_TEST_DRY_LOG_PRETTY = os.getenv(TEST_DRY_LOG_PRETTY_ENV_VAR)

ENV_SLS_CONSOLE_SETTINGS = os.getenv(SLS_CONSOLE_SETTINGS_ENV_VAR)

ENV_SLS_EXTENSION_LOG_LEVEL = os.getenv(SLS_EXTENSION_LOG_LEVEL_ENV_VAR)

ENV_OTEL_PYTHON_ENABLED_INSTRUMENTATIONS = os.getenv(OTEL_PYTHON_ENABLED_INSTRUMENTATIONS_ENV_VAR)
ENV_OTEL_PYTHON_DISABLED_INSTRUMENTATIONS = os.getenv(OTEL_PYTHON_DISABLED_INSTRUMENTATIONS_ENV_VAR)

ENV_SLS_EXTENSION_FLUSH_TIMEOUT = os.getenv(SLS_EXTENSION_FLUSH_TIMEOUT_ENV_VAR)
ENV_SLS_EXTENSION_COLLECTOR_URL = os.getenv(SLS_EXTENSION_COLLECTOR_URL_ENV_VAR)

ENV_OTEL_PYTHON_LOG_CORRELATION = os.getenv(OTEL_PYTHON_LOG_CORRELATION_ENV_VAR)

ENV__HANDLER = os.getenv(_HANDLER_ENV_VAR)
ENV_ORIG_HANDLER = os.getenv(ORIG_HANDLER_ENV_VAR)
