name: "Node: Publish @serverless/sdk-schema"

on:
  push:
    tags:
      - "@serverless/sdk-schema@[0-9]+.[0-9]+.[0-9]+"

jobs:
  publishNewSdkSchemaVersion:
    name: Publish new version
    runs-on: ubuntu-latest
    env:
      # It'll work with secrets.GITHUB_TOKEN (which is provided by GitHub unconditionally)
      # Still then release author would be "github-actions". It's better if it's dedicated repo bot
      GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Buf Setup
        uses: bufbuild/buf-setup-action@v1
      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - name: Retrieve ~/.npm from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-v16-${{ runner.os }}-refs/heads/main-${{ hashFiles('node/**package*.json') }}
          restore-keys: npm-v16-${{ runner.os }}-refs/heads/main-

      - name: Retrieve node_modules from cache
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: node/node_modules
          key: node-modules-v16-${{ runner.os }}-refs/heads/main-${{ hashFiles('node/package.json') }}
          restore-keys: node-modules-v16-${{ runner.os }}-refs/heads/main-A
      - name: Retrieve packages/sdk-schema/node_modules from cache
        id: cacheSdkSchemaNodeModules
        uses: actions/cache@v2
        with:
          path: node/packages/sdk-schema/node_modules
          key: packages/sdk-schema/node-modules-v16-${{ runner.os }}-refs/heads/main-${{ hashFiles('node/packages/sdk-schema/package.json') }}
          restore-keys: packages/sdk-schema/node-modules-v16-${{ runner.os }}-refs/heads/main-

      - name: Install main project dependencies
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: |
          cd node
          npm update --save-dev --no-save
      - name: Install packages/sdk-schema dependencies
        if: steps.cacheSdkSchemaNodeModules.outputs.cache-hit != 'true'
        run: |
          cd node/packages/sdk-schema
          npm install

      - name: Build Protobufs
        run: |
          cd ./proto
          buf build
          buf generate
      - name: Build
        run: |
          cd ./node/packages/sdk-schema
          npm run build
      - name: Publish New Version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ./node/packages/sdk-schema
          npm publish
      - name: Publish release notes
        run: |
          cd node/packages/sdk-schema
          TAG=${GITHUB_REF:10}
          npx github-release-from-cc-changelog $TAG
